### PR TITLE
added a real story

### PR DESCRIPTION
**Pull request by vasu404**
added a real story which gives reader a feeling of childhood nostalgia feeling. Btw the title was really nice

### CODE REVIEW

**Comment by vasu404** [comment]
forgot to mention:-
i have added the story of bunny and tortise. 
Regards

**Comment by vasu404** [comment]
Okay resolved now

**Comment by vasu404** [comment]
please merge, if it seems correct to you.

**Review by agarwaladitya0401 — COMMENTED** [review]
good work, buddy !

**Comment by agarwaladitya0401** [comment]
thanks for contri

**Comment by agarwaladitya0401** [comment]
hope to see more in future :)

**Pull request merged**
